/// Flutter icons ReevyIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReevyIcon
///      fonts:
///       - asset: fonts/ReevyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReevyIcon {
  ReevyIcon._();

  static const _kFontFam = 'ReevyIcon';
  static const String _kFontPkg = null;

  static const IconData vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData valid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
